import React from 'react';
import styles from './RulesPage.module.css';

export const RulesPage: React.FC = React.memo(() => {
  return (
    <section className={`${styles.notebookPage} notebook-page-bg`} aria-label="Rules & Instructions">
      <div className="page-top-margin"></div>
      <div className={styles.pageContent}>
        <h2 className={styles.handH2}>1.0 How to Decipher</h2>
        <p className={styles.handP}>
          A secret code is generated by the opponent (mainframe). It consists of exactly{' '}
          <strong>4 unique digits</strong>. The first digit is not zero (e.g.,{' '}
          <span className={styles.doodleText}>1024</span> is valid, but{' '}
          <span className={styles.doodleText}>0124</span> is not).
        </p>

        <h3 className={styles.handH3}>1.1 Deductive Indicators</h3>
        <ul className={styles.handList}>
          <li>
            <strong>Bulls (B)</strong>: Number of digits correct in both numeric value and placement slot.
          </li>
          <li>
            <strong>Cows (C)</strong>: Number of digits correct in value, but placed in the wrong slot.
          </li>
        </ul>

        <h3 className={styles.handH3}>1.2 Example Log</h3>
        <div className={styles.doodleWalkthrough}>
          <span className={styles.doodleHighlight}>Secret: 5 8 2 1</span>
          <div>Guess: 1 8 9 3</div>
          <div>
            Bulls: <span className={styles.circleDoodle}>1</span> (for 8)
          </div>
          <div>
            Cows: <span className={styles.circleDoodle}>1</span> (for 1)
          </div>
        </div>

        <h3 className={styles.handH3}>1.3 Directives</h3>
        <p className={styles.handP}>
          Systematically isolate digits. Tries are unlimited. Clear the board by starting a new round below.
        </p>

        <div className={styles.doodleBullCow} aria-hidden="true">
          <span className={styles.cowFace}>^..^</span>
          <span className={styles.bullFace}>:3</span>
        </div>
      </div>
    </section>
  );
});

RulesPage.displayName = 'RulesPage';
